server:
  port: 9090 # ????8080?????9090????

#配置数据库相关信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_management?serverTimezone=GMT%2b8&useSSL=false # ????
    username: root
    password: root
  application:
    name: springfox_swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  enable: true
#  application-name: ${spring.application.name}
#  application-version: 1.0
#  application-description: springfox swagger 3.0整合Demo
#  try-host: http://localhost:${server.port}




mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl